# Generated by Django 4.2.1 on 2023-06-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='tag',
            field=models.CharField(default='CCCCC', max_length=6),
        ),
    ]
