# Generated by Django 4.2.1 on 2023-06-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_disciplina_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='tag',
            field=models.CharField(default='CCCCC', max_length=7),
        ),
    ]
