# Generated by Django 4.2.1 on 2023-06-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_disciplina_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='professorhorario',
            name='horario_from',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='professorhorario',
            name='horario_to',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
