# Generated by Django 4.2.1 on 2023-06-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_professorhorario_disciplina'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='carga',
            field=models.IntegerField(default=30),
        ),
    ]
