# Generated by Django 4.2.1 on 2023-06-07 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_disciplina_dificuldade'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.disciplina'),
        ),
    ]
